services:
  app:
    build: .
    command: npm start
    container_name: acc-server-browser
    restart: unless-stopped
    ports:
      - "12300:3000"
    depends_on:
      - mongodb
    networks:
      - asb-network
    environment:
      - DB_URL=mongodb://mongodb:27017
    env_file:
      - .env
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - asbdata:/data/db
    networks:
      - asb-network

volumes:
  asbdata:

networks:
  asb-network:
    driver: bridge
